import './globals.css'
import {Provider} from './context/books'; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider>
    <html lang="en" className="bg-black flex flex-col items-center justify-between">
      <body>{children}</body>
    </html>
    </Provider>
  )
}
